
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      # Monta toda la carpeta backend. Esto incluye database/chatbot_data.db
      - ./backend:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app      
      - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]
    depends_on:
      - backend